### ISSUE TITLE
这种方式是不符合skynet对socket数据处理的设计

### ISSUE THREAD

**Issue by yuanfengyun** [chenweiqi/lua_httpsc#1]
你的这种方式不符合skynet框架对socket的处理啊。正确的方式应该是由skynet来处理socket数据收发，然后由上层来处理https逻辑。

**Comment by yuanfengyun** [comment]
阻塞的问题是要考虑的。至少也需要新开个线程来处理这种逻辑。

**Comment by chenweiqi** [comment]
skynet参考 [https_client示例 ](https://github.com/chenweiqi/lua_httpsc/blob/master/skynet_module/https_client.lua)
