### ISSUE TITLE
Skynet中使用https请求，导致进程崩溃了

### ISSUE THREAD

**Issue by msj456** [chenweiqi/lua_httpsc#3]
日志：
kernel: [10985297.133942] skynet[17469]: segfault at 20 ip 00007f8eea3c535a sp 00007f8eec9acca0 error 4 in httpsc.so[7f8eea1cc000+2e8000]

代码：
local https_c = skynet.newservice("https_client")
	local success, mess, opcode = skynet.call(https_c, "lua", "get", 
										"api.weixin.qq.com", 
										"/sns/jscode2session?appid=xxxx&secret=xxxxxxx&js_code="..code.."&grant_type=authorization_code")

	
	if success then
		print(mess, 1)
		local data = cjson.decode(mess);
		if data["errcode"] and tonumber(data["errcode"]) > 0 then
			print("wx login error2 = "..data["errcode"].." msg = "..data["errmsg"], 1)
		elseif data["openid"] then
			return data["openid"]
		end
	else
		print("wx login error1 = "..opcode, 1)
	end

**Comment by chenweiqi** [comment]
https_client 服务只能new一次

**Comment by msj456** [comment]
好的，谢谢
